name: chrismock
favicon: null
layout_spectrum: 0.5600135196000338
typography_spectrum: 0.23559088143520057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6694798897951841
  lightness: 0.7778543380554765
  saturation: 0.7708275769837201
  rhythmicContrast: 0.9721797865349799
purpose: []
